apiVersion: v1
kind: Service
metadata:
  name: glanz-keys-public
  labels:
    name: node-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: keys-api

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: production-keys
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: keys-api
    spec:
      containers:
      - name: keys-container
        image: 'gcr.io/glanz-250816/glanz-production-keys:v1c91ae2'
        env:
        - name: MONGO_PORT
          value: '27017'
        - name: MONGO_HOST
          value: 'mongo'  
        ports:
        - containerPort: 3000
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 10
          timeoutSeconds: 5
